# Generated by Django 5.2.3 on 2025-07-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='ram',
            field=models.CharField(default=4, max_length=15),
            preserve_default=False,
        ),
    ]
