# Generated by Django 5.2.3 on 2025-07-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_laptop_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
